//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriAxis.RunSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TriAxis.RunSharp.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiguous binding.
        /// </summary>
        internal static string ErrAmbiguousBinding {
            get {
                return ResourceManager.GetString("ErrAmbiguousBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion from &apos;{0}&apos; to &apos;{1}&apos; is ambiguous.
        /// </summary>
        internal static string ErrAmbiguousConversion {
            get {
                return ResourceManager.GetString("ErrAmbiguousConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexers for the type cannot have different names.
        /// </summary>
        internal static string ErrAmbiguousIndexerName {
            get {
                return ResourceManager.GetString("ErrAmbiguousIndexerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The switch type cannot be determined unambiguously.
        /// </summary>
        internal static string ErrAmbiguousSwitchExpression {
            get {
                return ResourceManager.GetString("ErrAmbiguousSwitchExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument count mismatch.
        /// </summary>
        internal static string ErrArgCountMismatch {
            get {
                return ResourceManager.GetString("ErrArgCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index must be greater than 0 and less than the number of arguments.
        /// </summary>
        internal static string ErrArgIndexOutOfRange {
            get {
                return ResourceManager.GetString("ErrArgIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must implement IConvertible.
        /// </summary>
        internal static string ErrArgMustImplementIConvertible {
            get {
                return ResourceManager.GetString("ErrArgMustImplementIConvertible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method can be used only on an array operand.
        /// </summary>
        internal static string ErrArrayOnly {
            get {
                return ResourceManager.GetString("ErrArrayOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name must be set when assembly is configured for saving.
        /// </summary>
        internal static string ErrAsmMissingSaveFile {
            get {
                return ResourceManager.GetString("ErrAsmMissingSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for attribute field &apos;{0}&apos; has already been defined.
        /// </summary>
        internal static string ErrAttributeMultiField {
            get {
                return ResourceManager.GetString("ErrAttributeMultiField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value for attribute property &apos;{0}&apos; has already been defined.
        /// </summary>
        internal static string ErrAttributeMultiProperty {
            get {
                return ResourceManager.GetString("ErrAttributeMultiProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set value for read-only attribute property &apos;{0}&apos;.
        /// </summary>
        internal static string ErrAttributeReadOnlyProperty {
            get {
                return ResourceManager.GetString("ErrAttributeReadOnlyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument passed by reference must have exactly the same type as the formal argument.
        /// </summary>
        internal static string ErrByRefTypeMismatch {
            get {
                return ResourceManager.GetString("ErrByRefTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot emit unreachable code.
        /// </summary>
        internal static string ErrCodeNotReachable {
            get {
                return ResourceManager.GetString("ErrCodeNotReachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use This() in a static method.
        /// </summary>
        internal static string ErrCodeStaticThis {
            get {
                return ResourceManager.GetString("ErrCodeStaticThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific chained constructor can be invoked only as the first statement in a constructor.
        /// </summary>
        internal static string ErrConstructorAlreadyChained {
            get {
                return ResourceManager.GetString("ErrConstructorAlreadyChained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method can be called only for instance constructor code.
        /// </summary>
        internal static string ErrConstructorOnlyCall {
            get {
                return ResourceManager.GetString("ErrConstructorOnlyCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event with custom accessors cannot be accessed as a field.
        /// </summary>
        internal static string ErrCustomEventFieldAccess {
            get {
                return ResourceManager.GetString("ErrCustomEventFieldAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The case with same value has already been defined.
        /// </summary>
        internal static string ErrDuplicateCase {
            get {
                return ResourceManager.GetString("ErrDuplicateCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method cannot be used on an instance method DynamicMethodGen.
        /// </summary>
        internal static string ErrDynamicMethodInstance {
            get {
                return ResourceManager.GetString("ErrDynamicMethodInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic methods cannot have custom attributes.
        /// </summary>
        internal static string ErrDynamicMethodNoCustomAttrs {
            get {
                return ResourceManager.GetString("ErrDynamicMethodNoCustomAttrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DynamicMethod hasn&apos;t been completed yet.
        /// </summary>
        internal static string ErrDynamicMethodNotCompleted {
            get {
                return ResourceManager.GetString("ErrDynamicMethodNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method can be used only on an instance method DynamicMethodGen.
        /// </summary>
        internal static string ErrDynamicMethodNotInstance {
            get {
                return ResourceManager.GetString("ErrDynamicMethodNotInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Else() called without a matching If().
        /// </summary>
        internal static string ErrElseWithoutIf {
            get {
                return ResourceManager.GetString("ErrElseWithoutIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index count mismatch.
        /// </summary>
        internal static string ErrIndexCountMismatch {
            get {
                return ResourceManager.GetString("ErrIndexCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface cannot define conversion operators.
        /// </summary>
        internal static string ErrInterfaceNoConversion {
            get {
                return ResourceManager.GetString("ErrInterfaceNoConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface cannot define a constructor.
        /// </summary>
        internal static string ErrInterfaceNoCtor {
            get {
                return ResourceManager.GetString("ErrInterfaceNoCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface cannot contain explicit interface implementations.
        /// </summary>
        internal static string ErrInterfaceNoExplicitImpl {
            get {
                return ResourceManager.GetString("ErrInterfaceNoExplicitImpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface cannot have fields.
        /// </summary>
        internal static string ErrInterfaceNoField {
            get {
                return ResourceManager.GetString("ErrInterfaceNoField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface cannot contain nested types.
        /// </summary>
        internal static string ErrInterfaceNoNested {
            get {
                return ResourceManager.GetString("ErrInterfaceNoNested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{1}&apos; of interface &apos;{0}&apos; is not implemented.
        /// </summary>
        internal static string ErrInterfaceNotImplemented {
            get {
                return ResourceManager.GetString("ErrInterfaceNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break() called outside of a loop or switch.
        /// </summary>
        internal static string ErrInvalidBreak {
            get {
                return ResourceManager.GetString("ErrInvalidBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ifTrue and ifFalse must be of the same type.
        /// </summary>
        internal static string ErrInvalidConditionalVariants {
            get {
                return ResourceManager.GetString("ErrInvalidConditionalVariants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue() called outside of a loop.
        /// </summary>
        internal static string ErrInvalidContinue {
            get {
                return ResourceManager.GetString("ErrInvalidContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert type from &apos;{0}&apos; to &apos;{1}&apos;.
        /// </summary>
        internal static string ErrInvalidConversion {
            get {
                return ResourceManager.GetString("ErrInvalidConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid delegate type.
        /// </summary>
        internal static string ErrInvalidDelegateType {
            get {
                return ResourceManager.GetString("ErrInvalidDelegateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either none or both &apos;Add&apos; and &apos;Remove&apos; event accessors must be defined.
        /// </summary>
        internal static string ErrInvalidEventAccessors {
            get {
                return ResourceManager.GetString("ErrInvalidEventAccessors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement can be used only in an exception block.
        /// </summary>
        internal static string ErrInvalidExceptionStatement {
            get {
                return ResourceManager.GetString("ErrInvalidExceptionStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field is accessed from an invalid context.
        /// </summary>
        internal static string ErrInvalidFieldContext {
            get {
                return ResourceManager.GetString("ErrInvalidFieldContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot transfer control out of a finally handler.
        /// </summary>
        internal static string ErrInvalidFinallyBranch {
            get {
                return ResourceManager.GetString("ErrInvalidFinallyBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided method must be either a MethodInfo or a ConstructorInfo.
        /// </summary>
        internal static string ErrInvalidMethodBase {
            get {
                return ResourceManager.GetString("ErrInvalidMethodBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operand.
        /// </summary>
        internal static string ErrInvalidOperand {
            get {
                return ResourceManager.GetString("ErrInvalidOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply operator &apos;{0}&apos; to operands of type &apos;{1}&apos;.
        /// </summary>
        internal static string ErrInvalidOperation {
            get {
                return ResourceManager.GetString("ErrInvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property is accessed from an invalid context.
        /// </summary>
        internal static string ErrInvalidPropertyContext {
            get {
                return ResourceManager.GetString("ErrInvalidPropertyContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement can be used only in a switch block.
        /// </summary>
        internal static string ErrInvalidSwitchStatement {
            get {
                return ResourceManager.GetString("ErrInvalidSwitchStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable is accessed from an invalid context.
        /// </summary>
        internal static string ErrInvalidVariableContext {
            get {
                return ResourceManager.GetString("ErrInvalidVariableContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable is accessed from an invalid scope.
        /// </summary>
        internal static string ErrInvalidVariableScope {
            get {
                return ResourceManager.GetString("ErrInvalidVariableScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method must provide a return value: {0}.
        /// </summary>
        internal static string ErrMethodMustReturnValue {
            get {
                return ResourceManager.GetString("ErrMethodMustReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find constructor.
        /// </summary>
        internal static string ErrMissingConstructor {
            get {
                return ResourceManager.GetString("ErrMissingConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target type doesn&apos;t have a default property.
        /// </summary>
        internal static string ErrMissingDefaultProperty {
            get {
                return ResourceManager.GetString("ErrMissingDefaultProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find event.
        /// </summary>
        internal static string ErrMissingEvent {
            get {
                return ResourceManager.GetString("ErrMissingEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find field.
        /// </summary>
        internal static string ErrMissingField {
            get {
                return ResourceManager.GetString("ErrMissingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find method.
        /// </summary>
        internal static string ErrMissingMethod {
            get {
                return ResourceManager.GetString("ErrMissingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find property.
        /// </summary>
        internal static string ErrMissingProperty {
            get {
                return ResourceManager.GetString("ErrMissingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access indexed property without indexes.
        /// </summary>
        internal static string ErrMissingPropertyIndex {
            get {
                return ResourceManager.GetString("ErrMissingPropertyIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; has already been set.
        /// </summary>
        internal static string ErrMultiAttribute {
            get {
                return ResourceManager.GetString("ErrMultiAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one parameter modifier is allowed out of [Ref, Out, Params].
        /// </summary>
        internal static string ErrMultiParamModifier {
            get {
                return ResourceManager.GetString("ErrMultiParamModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member visibility can be set only once.
        /// </summary>
        internal static string ErrMultiVisibility {
            get {
                return ResourceManager.GetString("ErrMultiVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member virtual type can be set only once.
        /// </summary>
        internal static string ErrMultiVTable {
            get {
                return ResourceManager.GetString("ErrMultiVTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot emit code for an abstract or runtime-provided method.
        /// </summary>
        internal static string ErrNoCodeAllowed {
            get {
                return ResourceManager.GetString("ErrNoCodeAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no block that can be closed by this method.
        /// </summary>
        internal static string ErrNoOpenBlocks {
            get {
                return ResourceManager.GetString("ErrNoOpenBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot complete code as there are some remaining opened blocks.
        /// </summary>
        internal static string ErrOpenBlocksRemaining {
            get {
                return ResourceManager.GetString("ErrOpenBlocksRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operand of type &apos;{0}&apos; cannot be read.
        /// </summary>
        internal static string ErrOperandNotReadable {
            get {
                return ResourceManager.GetString("ErrOperandNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address of operand of type &apos;{0}&apos; cannot be retrieved.
        /// </summary>
        internal static string ErrOperandNotReferencible {
            get {
                return ResourceManager.GetString("ErrOperandNotReferencible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operand of type &apos;{0}&apos; cannot be written.
        /// </summary>
        internal static string ErrOperandNotWritable {
            get {
                return ResourceManager.GetString("ErrOperandNotWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter array must be the last parameter defined.
        /// </summary>
        internal static string ErrParamArrayMustBeLast {
            get {
                return ResourceManager.GetString("ErrParamArrayMustBeLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter array must be defined using an array type.
        /// </summary>
        internal static string ErrParamArrayNotArray {
            get {
                return ResourceManager.GetString("ErrParamArrayNotArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown parameter: {0}.
        /// </summary>
        internal static string ErrParamUnknown {
            get {
                return ResourceManager.GetString("ErrParamUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value type constructor cannot invoke a base constructor.
        /// </summary>
        internal static string ErrStructNoBaseCtor {
            get {
                return ResourceManager.GetString("ErrStructNoBaseCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value types cannot have default constructors.
        /// </summary>
        internal static string ErrStructNoDefaultCtor {
            get {
                return ResourceManager.GetString("ErrStructNoDefaultCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is already completed.
        /// </summary>
        internal static string ErrTypeAlreadyCompleted {
            get {
                return ResourceManager.GetString("ErrTypeAlreadyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided type must be a delegate type.
        /// </summary>
        internal static string ErrTypeMustBeDelegate {
            get {
                return ResourceManager.GetString("ErrTypeMustBeDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type hasn&apos;t been completed yet.
        /// </summary>
        internal static string ErrTypeNotCompleted {
            get {
                return ResourceManager.GetString("ErrTypeNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable used without having been initialized.
        /// </summary>
        internal static string ErrUninitializedVarAccess {
            get {
                return ResourceManager.GetString("ErrUninitializedVarAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable accessed before it&apos;s type was defined.
        /// </summary>
        internal static string ErrUntypedVarAccess {
            get {
                return ResourceManager.GetString("ErrUntypedVarAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot return value from a void method.
        /// </summary>
        internal static string ErrVoidMethodReturningValue {
            get {
                return ResourceManager.GetString("ErrVoidMethodReturningValue", resourceCulture);
            }
        }
    }
}
